- name: install packages
  hosts: localhost
  connection: local
  tasks:
  - name: print package names
    ansible.builtin.package:
      name: "{{ item }}"
      state: latest
    loop:
    - nginx
    - mysql
    - zip 
    